#!/usr/bin/env python3
"""
Generates _INDEX.md for the Obsidian vault.
Lists every note in World/ and Campaigns/ with path, tags, and aliases.
Usage: python3 scripts/generate_index.py
Run from the vault/ directory.
No external dependencies required.
"""

import os
import re
from pathlib import Path
from collections import defaultdict

VAULT = Path(__file__).resolve().parent.parent
FOLDERS = ["World", "Campaigns"]
OUTPUT = VAULT / "_INDEX.md"


def extract_frontmatter(filepath: Path) -> dict:
    """Extract tags and aliases from YAML frontmatter without PyYAML."""
    try:
        text = filepath.read_text(encoding="utf-8")
    except Exception:
        return {}

    match = re.match(r"^---\s*\n(.*?)\n---", text, re.DOTALL)
    if not match:
        return {}

    block = match.group(1)
    tags = []
    aliases = []

    current_key = None
    for line in block.split("\n"):
        stripped = line.strip()
        # Detect top-level key
        if re.match(r"^(tags|aliases)\s*:", line):
            current_key = line.split(":")[0].strip()
            # Check for inline value like "aliases: [Foo, Bar]"
            after = line.split(":", 1)[1].strip()
            if after.startswith("["):
                items = after.strip("[]").split(",")
                items = [i.strip().strip("'\"") for i in items if i.strip()]
                if current_key == "tags":
                    tags = items
                elif current_key == "aliases":
                    aliases = items
                current_key = None
            continue
        elif re.match(r"^\w", line) and ":" in line:
            current_key = None
            continue

        # List item under current key
        if current_key and stripped.startswith("- "):
            val = stripped[2:].strip().strip("'\"")
            if val:
                if current_key == "tags":
                    tags.append(val)
                elif current_key == "aliases":
                    aliases.append(val)

    return {"tags": tags, "aliases": aliases}


def build_index():
    entries = []

    for folder in FOLDERS:
        folder_path = VAULT / folder
        if not folder_path.exists():
            continue
        for md in sorted(folder_path.rglob("*.md")):
            fm = extract_frontmatter(md)
            name = md.stem
            rel = str(md.relative_to(VAULT))
            aliases = fm.get("aliases", [])
            tags = fm.get("tags", [])

            entries.append({
                "name": name,
                "path": rel,
                "aliases": aliases,
                "tags": tags,
            })

    # Group by subfolder (World/People, World/Locations, Campaigns/Era da Ascensão, etc.)
    groups = defaultdict(list)
    for e in entries:
        parts = Path(e["path"]).parts
        if len(parts) >= 2:
            group = f"{parts[0]}/{parts[1]}"
        else:
            group = parts[0]
        groups[group].append(e)

    # Generate markdown
    lines = [
        "---",
        "tags: []",
        "aliases: []",
        "---",
        "",
        "# Vault Index",
        "",
        f"> Auto-generated by `scripts/generate_index.py`. **{len(entries)} notes** indexed.",
        "> Re-run the script after adding or renaming notes.",
        "",
    ]

    for group_key in sorted(groups.keys()):
        group_entries = groups[group_key]
        lines.append(f"## {group_key}")
        lines.append("")
        lines.append("| Note | Aliases | Tags | Path |")
        lines.append("|------|---------|------|------|")
        for e in sorted(group_entries, key=lambda x: x["name"].lower()):
            alias_str = ", ".join(e["aliases"]) if e["aliases"] else "—"
            tag_str = ", ".join(f"`{t}`" for t in e["tags"]) if e["tags"] else "—"
            lines.append(f"| [[{e['name']}]] | {alias_str} | {tag_str} | `{e['path']}` |")
        lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUTPUT} with {len(entries)} notes")


if __name__ == "__main__":
    build_index()
